services:
  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_DB: job_tracking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"